[package]
name = "hornet"
version = "0.1.0"
description = "A load testing tool"
repository = "https://github.com/hornet-test/hornet"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
